#!/usr/bin/env bash
# display the information about subdomains.

domain_info() {
	domain=$1
	subdomain=$2
	result=$(dig +short "$subdomain.$domain")
	record=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
	echo "The subdomain $subdomain is a $record record and points to $result"
}

if [ $# -eq 1 ]; then
	domain_info "$1" "www"
	domain_info "$1" "lb-01"
	domain_info "$1" "web-01"
	domain_info "$1" "web-02"
elif [ $# -eq 2 ]; then
	domain_info "$1" "$2"
fi
