#!/usr/bin/env bash
# Configure Nginx server to redirect to another page.

sudo apt update -y
sudo apt install nginx -y
sudo ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html 
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;" /etc/nginx/sites-available/default
sudo service nginx restart

