#!/usr/bin/env bash
# Configure Nginx server to redirect to another page.

sudo apt-get update
sudo apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html
echo "server {
	listen 80;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index  index.html index.htm;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > /etc/nginx/sites-available/default

service nginx restart

