#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page containing the string
# ... "Ceci n'est pas une page".

sudo apt-get update
sudo apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/htmlindex/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

echo "server {
	listen 80;
	
	error_page 404 /404.html;
	location /404 {
		root /etc/nginx/html;
		internal;
	}
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > /etc/nginx/sites-available/default

service nginx restart

