#!/usr/bin/env bash
# Configure Nginx to listen port 80
systemctl start nginx
if ! netstat -tuln | grep -q ':80'; then
    sed -i '/listen\s*80;/ s/$/ default_server;/' \
    	/etc/nginx/sites-available/default
	systemctl restart nginx
fi
