#!/usr/bin/env bash
# Check if Nginx is running
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to listen port 80
sudo sed -i '/listen\s*80;/ s/$/ default_server;/' \
    /etc/nginx/sites-available/default
sudo service nginx restart
