#!/usr/bin/env bash
# Script that configure and execute nginx to listen on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx stop
sudo service nginx start
