#!/usr/bin/env bash
# Script to configure nginx and stop it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx stop >/dev/null 2>&1
