#!/usr/bin/env bash
# scrip to create and display various processes and signals files
file=/var/run/myscript.pid
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm "$file; exit"' SIGQUIT
trap 'echo "I hate the kill command; rm $file; exit"' SIGTERM
echo $$ > "$file"
while :
do
	echo "To infinity and beyond"
	sleep 2
done
