#!/usr/bin/env bash
# Fix the container so that nginx is running as the nginx user.
pkill apache2
# Modify nhinx configuration to tun as nginx user
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
# Modify nginx configuration to listen on part 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
