#!/usr/bin/env bash
# SSH config such as connecting to server without password


Host *
   PasswordAuthentication no
   IdentifyFile ~/.ssh/school
   SendEnv LANG LC_*
   HashKnownHosts yes
   GSSAPIAuthentication yes
   GSSAPIDelegateCredentials no
